
name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    shell: 'script -q -e -c "bash {0}"' # add support for colors in output. see: https://github.com/actions/runner/issues/241

jobs:
  test:
    name: Test Code
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '20.11.0'
    - run: npm ci --no-audit --no-fund
    - run: dotenv -e .env.test.local -- npm run compile
    - run: npm test

